### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by jkwill87** [mesonbuild/glfw3#1]
@legeana The repository has no releases and `meson wrap install glfw3` fails.

**Comment by eli-schwartz** [comment]
Duplicate of https://github.com/mesonbuild/wrapdb/issues/27

Someone requested to make a new wrap in https://github.com/mesonbuild/wrapdb/issues/15; the repository was duly created, but no PR to implement the wrap showed up.

You're welcome to submit one. :)

**Comment by eli-schwartz** [comment]
Duplicate of mesonbuild/wrapdb#27
